---
# tasks file for ansible-role-openscap
- name: install openscap scanner
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openscap-scanner
    - scap-security-guide

- name: run openscap scan
  command: oscap xccdf eval \
    --profile xccdf_org.ssgproject.content_profile_{{ ansible_role_openscap_oscap_profile }} \
    --results {{ ansible_role_openscap_datadir }}/scan.xml \
    --report {{ ansible_role_openscap_datadir }}/scan-report.html \
    /usr/share/xml/scap/ssg/content/ssg-rhel{{ ansible_distribution_major_version }}-ds.xml
  ignore_errors: yes

- name: remediate system
  command: oscap xccdf eval \
    --remediate \
    --profile xccdf_org.ssgproject.content_profile_{{ ansible_role_openscap_oscap_profile }} \
    --results {{ ansible_role_openscap_datadir }}/scan.xml \
    /usr/share/xml/scap/ssg/content/ssg-rhel{{ ansible_distribution_major_version }}-ds.xml
  when: ansible_role_openscap_remediate

- name: upload scap report to Red Hat Cloud Management Services
  command: insights-client \
    --verbose \
    --payload {{ ansible_role_openscap_datadir }}/scan.xml \
    --content-type application/vnd.redhat.compliance.something+tgz
  when: ansible_role_openscap_upload
